[project]
name = "chemeqbalancer"
version = "1.0.0"
description = "Balance chemical equations using linear algebra."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "streamlit>=1.50.0",
    "sympy>=1.14.0",
]
